version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directories:
      - /windows/MyProxy
      - /windows/MyProxy/Tests
      - /linux/MyProxyLinux/core
      - /linux/MyProxyLinux/cli
      - /linux/MyProxyLinux/gui
      - /linux/MyProxyLinux/tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dotnet-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gradle
    directory: /android/MyProxyAndroid
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      android-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
